#!/usr/bin/env python
# -*- coding: utf-8 -*-

# '''noteiro q emite quantia em $ de acordo com o valor solicitado vsolic usando
# 	as notas ndispxxx. somente caucula quantas notas de cada valor necessarioas para operacao.
#	sugere q senhas e  saldo ja validados.'''


ndisp100 = 10
ndisp050 = 10
ndisp020 = 10
ndisp010 = 10
ndisp005 = 10
ndisp002 = 10

vsolic = int(raw_input("qual valor solicitado  \n \n"))

if vsolic >= 100 and ndisp100 > 0:
    nalib100 = vsolic / 100
    if ndisp100 >= nalib100:
        vsolic = vsolic - (nalib100 * 100)
        ndisp100 = ndisp100 - nalib100
    else:
        vsolic = vsolic - (ndisp100 * 100)
        ndisp100 = 0

if vsolic >= 50 and ndisp050 > 0:
    nalib050 = vsolic / 50
    if ndisp050 >= nalib050:
        vsolic = vsolic - (nalib050 * 50)
        ndisp050 = ndisp050 - nalib050
    else:
        vsolic = vsolic - (ndisp050 * 50)
        ndisp100 = 0

if vsolic >= 20 and ndisp020 > 0:
    nalib020 = vsolic / 20
    if ndisp020 >= nalib020:
        vsolic = vsolic - (nalib020 * 20)
        ndisp020 = ndisp020 - nalib020
    else:
        vsolic = vsolic - (ndisp020 * 20)
        ndisp020 = 0

if vsolic >= 10 and ndisp010 > 0:
    nalib010 = vsolic / 10
    if ndisp010 >= nalib010:
        vsolic = vsolic - (nalib010 * 10)
        ndisp010 = ndisp010 - nalib010
    else:
        vsolic = vsolic - (ndisp010 * 10)
        ndisp010 = 0

if vsolic >= 5 and ndisp005 > 0:
    nalib005 = vsolic / 5
    if ndisp005 >= nalib005:
        vsolic = vsolic - (nalib005 * 5)
        ndisp005 = ndisp005 - nalib005
    else:
        vsolic = vsolic - (ndisp005 * 5)
        ndisp005 = 0

if vsolic >= 2 and ndisp002 > 0:
    nalib002 = vsolic / 2
    if ndisp002 >= nalib002:
        vsolic = vsolic - (nalib002 * 2)
        ndisp002 = ndisp002 - nalib002
    else:
        vsolic = vsolic - (ndisp002 * 2)
        ndisp002 = 0

print ("notas disponiveis de 100 = "), ndisp100
print ("notas disponiveis de 050 = "), ndisp050
print ("notas disponiveis de o20 = "), ndisp020
print ("notas disponiveis de 010 = "), ndisp010
print ("notas disponiveis de 005 = "), ndisp005
print ("notas disponiveis de 002 = "), ndisp002


