#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
 '''noteiro q emite quantia em $ de acordo com o valor solicitado vsolic usando
 as notas ndispxxx. somente caucula quantas notas de cada valor necessarioas para operacao.
 sugere q senhas e  saldo ja validados.'''
 
 
ndisp100 = 10
ndisp050 = 10
ndisp020 = 10
ndisp010 = 10
ndisp005 = 10
ndisp002 = 10

vsolic = raw_input("qual valor solicitado")

if vsolic >= 100 and ndisp100 > 0 :
    nalib100 = vsolic/100
    if ndisp100 >= nalib100 :
        vsolic = vsolic - (nalib100 * 100)
        ndisp100 = ndisp100 - nalib100
    else :
        vsolic = vsolic - (ndisp100 * 100)
        ndisp100 = 0
        
        
print vsolic ,ndisp100
